name: Run Ansible in GitHub Action

on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      ANSIBLE_HOST_KEY_CHECKING: False
    steps:
      - name: Show Ansible information
        run: ansible-playbook --version

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Create AWS EC2 instances
        id: create_aws_ec2_instances
        uses: ./.github/actions/ec2-create-instances
        with:
          region: ${{ inputs.region }}
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: Set inventory file name
        id: get_inventory_name
        run: ls -1 *_inventory.yaml >> $GITHUB_OUTPUT

      - name: Start the Hyperfoil controller
        id: start_hyperfoil_controller
        uses: ./.github/actions/hyperfoil-create-controller
        with:
          inventory: ${{ steps.get_inventory_name.outputs.out }}

      - name: Started controller
        run: echo "Started"

      - name: Delete EC2 instances
        if: ${{ always() && steps.create_aws_ec2_instances.conclusion != 'skipped' }}
        uses: ./.github/actions/ec2-delete-instances
        with:
          region: ${{ inputs.region }}
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
